# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/usr/bin/ccache
CC=/usr/bin/clang
MRC=/usr/bin/llvm-rc
MM=/usr/bin/clang
CXX=/usr/bin/clang
AS=/usr/bin/clang
MXX=/usr/bin/clang

LD=/usr/bin/clang++
AR=/usr/bin/ar
SH=/usr/bin/clang++

test_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/include -std=c++2b -DNDEBUG
test_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/include -std=c++2b -DNDEBUG
test_LDFLAGS=-m64 -L/home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/lib -Lbuild/linux/x86_64/release -L/usr/lib -s -lgtest -lgtest_main -lgmock -llibciphervault -lfmt -lssl -lcrypto -lpthread
bench_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/include -std=c++2b -DNDEBUG
bench_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/include -std=c++2b -DNDEBUG
bench_LDFLAGS=-m64 -L/home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/lib -Lbuild/linux/x86_64/release -L/usr/lib -s -lbenchmark_main -lbenchmark -llibciphervault -lfmt -lssl -lcrypto -lpthread
libciphervault_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -isystem /home/pablo/.xmake/packages/t/tabulate/1.4/f332da4973a7470eb1f7ff02b32fe5d6/include -std=c++2b -DNDEBUG
libciphervault_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -isystem /home/pablo/.xmake/packages/t/tabulate/1.4/f332da4973a7470eb1f7ff02b32fe5d6/include -std=c++2b -DNDEBUG
libciphervault_ARFLAGS=-cr
ciphervault_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -isystem /home/pablo/.xmake/packages/t/tabulate/1.4/f332da4973a7470eb1f7ff02b32fe5d6/include -std=c++2b -DNDEBUG
ciphervault_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -isystem /home/pablo/.xmake/packages/t/tabulate/1.4/f332da4973a7470eb1f7ff02b32fe5d6/include -std=c++2b -DNDEBUG
ciphervault_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -L/usr/lib -s -llibciphervault -lfmt -lssl -lcrypto

default:  test bench libciphervault ciphervault

all:  test bench libciphervault ciphervault

.PHONY: default all  test bench libciphervault ciphervault

test: build/linux/x86_64/release/test
build/linux/x86_64/release/test: build/linux/x86_64/release/liblibciphervault.a build/.objs/test/linux/x86_64/release/test/cert/cert_rsa_tests.cpp.o build/.objs/test/linux/x86_64/release/test/cert/cert_dsa_tests.cpp.o build/.objs/test/linux/x86_64/release/test/main.cpp.o
	@echo linking.release test
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/test build/.objs/test/linux/x86_64/release/test/cert/cert_rsa_tests.cpp.o build/.objs/test/linux/x86_64/release/test/cert/cert_dsa_tests.cpp.o build/.objs/test/linux/x86_64/release/test/main.cpp.o $(test_LDFLAGS) > build/.build.log 2>&1

build/.objs/test/linux/x86_64/release/test/cert/cert_rsa_tests.cpp.o: test/cert/cert_rsa_tests.cpp
	@echo ccache compiling.release test/cert/cert_rsa_tests.cpp
	@mkdir -p build/.objs/test/linux/x86_64/release/test/cert
	@$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/release/test/cert/cert_rsa_tests.cpp.o test/cert/cert_rsa_tests.cpp > build/.build.log 2>&1

build/.objs/test/linux/x86_64/release/test/cert/cert_dsa_tests.cpp.o: test/cert/cert_dsa_tests.cpp
	@echo ccache compiling.release test/cert/cert_dsa_tests.cpp
	@mkdir -p build/.objs/test/linux/x86_64/release/test/cert
	@$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/release/test/cert/cert_dsa_tests.cpp.o test/cert/cert_dsa_tests.cpp > build/.build.log 2>&1

build/.objs/test/linux/x86_64/release/test/main.cpp.o: test/main.cpp
	@echo ccache compiling.release test/main.cpp
	@mkdir -p build/.objs/test/linux/x86_64/release/test
	@$(CXX) -c $(test_CXXFLAGS) -o build/.objs/test/linux/x86_64/release/test/main.cpp.o test/main.cpp > build/.build.log 2>&1

bench: build/linux/x86_64/release/bench
build/linux/x86_64/release/bench: build/linux/x86_64/release/liblibciphervault.a build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_rsa_benchmarks.cpp.o build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_dsa_benchmarks.cpp.o build/.objs/bench/linux/x86_64/release/bench/main.cpp.o
	@echo linking.release bench
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/bench build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_rsa_benchmarks.cpp.o build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_dsa_benchmarks.cpp.o build/.objs/bench/linux/x86_64/release/bench/main.cpp.o $(bench_LDFLAGS) > build/.build.log 2>&1

build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_rsa_benchmarks.cpp.o: bench/cipher/cipher_rsa_benchmarks.cpp
	@echo ccache compiling.release bench/cipher/cipher_rsa_benchmarks.cpp
	@mkdir -p build/.objs/bench/linux/x86_64/release/bench/cipher
	@$(CXX) -c $(bench_CXXFLAGS) -o build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_rsa_benchmarks.cpp.o bench/cipher/cipher_rsa_benchmarks.cpp > build/.build.log 2>&1

build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_dsa_benchmarks.cpp.o: bench/cipher/cipher_dsa_benchmarks.cpp
	@echo ccache compiling.release bench/cipher/cipher_dsa_benchmarks.cpp
	@mkdir -p build/.objs/bench/linux/x86_64/release/bench/cipher
	@$(CXX) -c $(bench_CXXFLAGS) -o build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_dsa_benchmarks.cpp.o bench/cipher/cipher_dsa_benchmarks.cpp > build/.build.log 2>&1

build/.objs/bench/linux/x86_64/release/bench/main.cpp.o: bench/main.cpp
	@echo ccache compiling.release bench/main.cpp
	@mkdir -p build/.objs/bench/linux/x86_64/release/bench
	@$(CXX) -c $(bench_CXXFLAGS) -o build/.objs/bench/linux/x86_64/release/bench/main.cpp.o bench/main.cpp > build/.build.log 2>&1

libciphervault: build/linux/x86_64/release/liblibciphervault.a
build/linux/x86_64/release/liblibciphervault.a: build/.objs/libciphervault/linux/x86_64/release/src/libciphervault/cert.cpp.o
	@echo linking.release liblibciphervault.a
	@mkdir -p build/linux/x86_64/release
	@$(AR) $(libciphervault_ARFLAGS) build/linux/x86_64/release/liblibciphervault.a build/.objs/libciphervault/linux/x86_64/release/src/libciphervault/cert.cpp.o > build/.build.log 2>&1

build/.objs/libciphervault/linux/x86_64/release/src/libciphervault/cert.cpp.o: src/libciphervault/cert.cpp
	@echo ccache compiling.release src/libciphervault/cert.cpp
	@mkdir -p build/.objs/libciphervault/linux/x86_64/release/src/libciphervault
	@$(CXX) -c $(libciphervault_CXXFLAGS) -o build/.objs/libciphervault/linux/x86_64/release/src/libciphervault/cert.cpp.o src/libciphervault/cert.cpp > build/.build.log 2>&1

ciphervault: build/linux/x86_64/release/ciphervault
build/linux/x86_64/release/ciphervault: build/linux/x86_64/release/liblibciphervault.a build/.objs/ciphervault/linux/x86_64/release/src/main.cpp.o
	@echo linking.release ciphervault
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/ciphervault build/.objs/ciphervault/linux/x86_64/release/src/main.cpp.o $(ciphervault_LDFLAGS) > build/.build.log 2>&1

build/.objs/ciphervault/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.release src/main.cpp
	@mkdir -p build/.objs/ciphervault/linux/x86_64/release/src
	@$(CXX) -c $(ciphervault_CXXFLAGS) -o build/.objs/ciphervault/linux/x86_64/release/src/main.cpp.o src/main.cpp > build/.build.log 2>&1

clean:  clean_test clean_bench clean_libciphervault clean_ciphervault

clean_test:  clean_libciphervault
	@rm -rf build/linux/x86_64/release/test
	@rm -rf build/linux/x86_64/release/test.sym
	@rm -rf build/.objs/test/linux/x86_64/release/test/cert/cert_rsa_tests.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/release/test/cert/cert_dsa_tests.cpp.o
	@rm -rf build/.objs/test/linux/x86_64/release/test/main.cpp.o

clean_bench:  clean_libciphervault
	@rm -rf build/linux/x86_64/release/bench
	@rm -rf build/linux/x86_64/release/bench.sym
	@rm -rf build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_rsa_benchmarks.cpp.o
	@rm -rf build/.objs/bench/linux/x86_64/release/bench/cipher/cipher_dsa_benchmarks.cpp.o
	@rm -rf build/.objs/bench/linux/x86_64/release/bench/main.cpp.o

clean_libciphervault: 
	@rm -rf build/linux/x86_64/release/liblibciphervault.a
	@rm -rf build/linux/x86_64/release/libciphervault.sym
	@rm -rf build/.objs/libciphervault/linux/x86_64/release/src/libciphervault/cert.cpp.o

clean_ciphervault:  clean_libciphervault
	@rm -rf build/linux/x86_64/release/ciphervault
	@rm -rf build/linux/x86_64/release/ciphervault.sym
	@rm -rf build/.objs/ciphervault/linux/x86_64/release/src/main.cpp.o

