name: CI/CD
# Only deploy when a new tag is pushed
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  discussions: write
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    name: Build, test and deploy
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker-Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: ${PWD}/scripts/build
      - name: Test
        run: ${PWD}/scripts/test
      - name: Publish
        run: ${PWD}/scripts/publish
      - name: Pack
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ciphervault.zip ciphervault
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "ciphervault.zip"
    # - name: Build Docker image
    #   run: docker build -t tomcat0x42/ciphervault .
    # - name: Create Docker container
    #   run: docker create --name ciphervault-container tomcat0x42/ciphervault-container
    # - name: Copy out the files
    #   run: docker cp ciphervault-container:/project/src/build/${APP_NAME}.uf2 ./${APP_NAME}.uf2
    # - name: Put environment variable into the env context
    #   run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
    # - name: Push to release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: ${{ env.app_name }}.uf2
    #     body_path: CHANGELOG.md
